### ISSUE TITLE
TG222 is missing pin 13, 14 and 15

### ISSUE THREAD

**Issue by andlier** [lemcu/EFM32-Eagle-Library#1]
TG222 is missing pin 13, 14 and 15.
I haven't checked other packages, but the schematic symbol for TG222 is at least missing these 3 pins.

**Comment by viswesr** [comment]
Confirmed. This issue exist in some other parts as well. Working on a fix

**Comment by viswesr** [comment]
Any port pin in CSV file which does not have alternate function is missing as in "13;PA8;Unknown;", The regular expression for identifying port-pin expects a string like "12;PB8;Unknown;LFXTAL_N / TIM1_CC1 #3 / US0_RX #4 / US1_CS #0" with functionality.

A very small change is required in Tattanii-Script.
